### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by bourla77** [zimmerle/GSM-Shark#1]
[  3%] Building CXX object src/CMakeFiles/gsm-shark.dir/main.cpp.o
In file included from /root/Desktop/GSM-Shark/src/scanengine.h:32:0,
                 from /root/Desktop/GSM-Shark/src/mainwin.h:33,
                 from /root/Desktop/GSM-Shark/src/main.cpp:25:
/root/Desktop/GSM-Shark/src/gnuradioworker.h:30:10: fatal error: gr_uhd_api.h: No such file or directory
 #include <gr_uhd_api.h>
          ^~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/gsm-shark.dir/build.make:129: recipe for target 'src/CMakeFiles/gsm-shark.dir/main.cpp.o' failed
make[2]: *** [src/CMakeFiles/gsm-shark.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/gsm-shark.dir/all' failed
make[1]: *** [src/CMakeFiles/gsm-shark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zimmerle** [comment]
Hi @bourla77,

Thanks for your interest in the project. The truth is that this code is not really workable. Do you have any particular interest in the subject?

**Comment by bourla77** [comment]
I'm learning the gsm basics so I wanted a scanner to see the cell
parameters, if you know other projects that can see radio parameters like
CID LAC BSIC and more , let me know
Thanks for contacting
Tal.

**Comment by zimmerle** [comment]
I would suggest the utilization of http://bb.osmocom.org/trac/ and/or https://github.com/ptrkrysik/gr-gsm IMHO, those are the project that contains more information about the subject.

**Comment by bourla77** [comment]
Thanks!
